logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

spring:
  cloud:
    inetutils:
      ignored-interfaces: eth1*
      preferred-networks: 192.168
  datasource:
    url: jdbc:h2:mem:notification_test_db;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations: classpath*:schema/create.sql
      #data-locations: classpath*:schema/insert.sql
      encoding: UTF-8
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: ${AWS_SMTP_HOST}
    port: ${AWS_SMTP_PORT}
    username: ${AWS_SMTP_USERNAME}
    password: ${AWS_SMTP_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

aws-mail:
  from: ${AWS_MAIL_FROM}

test-to-mail: dblys152@gmail.com

cool-sms:
  key: ${COOL_SMS_KEY}
  secret: ${COOL_SMS_SECRET}
  from: ${COOL_SMS_FROM}

api-key:
  header: X-API-Key
  value:
    notification: ${NOTIFICATION_API_KEY}
