CREATE TABLE IF NOT EXISTS NOTIFICATION_LIST
(
    NOTIFICATION_ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE                VARCHAR(30)     NOT NULL,
    STATUS              VARCHAR(30)     NOT NULL,
    SENT_AT             TIMESTAMP WITH TIME ZONE NOT NULL,
    SENDER_TYPE         VARCHAR(30)     NOT NULL,
    SENDER_USER_ID      VARCHAR(39),
    DESTINATION         VARCHAR(30)     NOT NULL,
    RECEIVER_TYPE       VARCHAR(30)     NOT NULL,
    RECEIVER_ID         VARCHAR(39),
    TITLE               VARCHAR(200)    NOT NULL,
    CONTENTS            TEXT            NOT NULL,
    CREATED_AT          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    MODIFIED_AT         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    DELETED_AT          TIMESTAMP WITH TIME ZONE
);