CREATE TABLE IF NOT EXISTS NOTIFICATIONS
(
    NOTIFICATION_ID     BIGINT PRIMARY KEY,
    TYPE                VARCHAR(30)     NOT NULL,
    STATUS              VARCHAR(30)     NOT NULL,
    SENT_AT             TIMESTAMP WITH TIME ZONE NOT NULL,
    DESTINATION         VARCHAR(30)     NOT NULL,
    TITLE               VARCHAR(200)    NOT NULL,
    CONTENTS            TEXT            NOT NULL,
    SENDER_TYPE         VARCHAR(30)     NOT NULL,
    SENDER_USER_ID      VARCHAR(39),
    RECEIVER_TYPE       VARCHAR(30)     NOT NULL,
    RECEIVER_ID         VARCHAR(39),
    CREATED_AT          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    MODIFIED_AT         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);